pastomatai/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using pastomatai.Models;

namespace pastomatai.Controllers
{
    public class DeliveryController : Controller
    {
        private readonly pastomataiContext _context;

        public DeliveryController(pastomataiContext context)
        {
            _context = context;
        }

        //GET: Delivery
        public IActionResult Index(string state, bool hasterminal, string terminalId, string postMachineId, bool haspostmachine)
        {
            if (!String.IsNullOrEmpty(terminalId))
            {
                if (String.IsNullOrEmpty(state))
                {
                    var pastomataiContext = _context.Package.Include(p => p.FkEndUseridEndUserNavigation)
                                .Include(p => p.FkLoggedInUseridEndUserNavigation)
                                .Include(p => p.FkTerminalidTerminalNavigation);
                    ViewBag.FkTerminalidTerminal = GetTerminalAddressList();
                    ViewBag.PostMachines = GetPostMachineAddressList();
                    ViewData["TerminalFilter"] = terminalId;
                    return View(pastomataiContext);
                }
                else if (hasterminal == false)
                {
                    var id = Int16.Parse(terminalId);
                    var pastomataiContext = _context.Package.Include(p => p.FkEndUseridEndUserNavigation)
                        .Include(p => p.FkLoggedInUseridEndUserNavigation)
                        .Include(p => p.FkTerminalidTerminalNavigation)
                        .Where(p => p.PackageState.Contains(state))
                        .Where(p => p.FkTerminalidTerminal.HasValue.Equals(hasterminal));
                    ViewBag.FkTerminalidTerminal = GetTerminalAddressList();
                    ViewBag.PostMachines = GetPostMachineAddressList();
                    ViewData["TerminalFilter"] = terminalId;
                    return View(pastomataiContext);
                }
                else
                {
                    var id = Int16.Parse(terminalId);
                    var pastomataiContext = _context.Package.Include(p => p.FkEndUseridEndUserNavigation)
                        .Include(p => p.FkLoggedInUseridEndUserNavigation)
                        .Include(p => p.FkTerminalidTerminalNavigation)
                        .Where(p => p.PackageState.Contains(state))
                        .Where(p => p.FkTerminalidTerminal.HasValue.Equals(hasterminal))
                        .Where(p => p.FkTerminalidTerminalNavigation.IdTerminal.Equals(id));
                    ViewBag.FkTerminalidTerminal = GetTerminalAddressList();
                    ViewBag.PostMachines = GetPostMachineAddressList();
                    ViewData["TerminalFilter"] = terminalId;
                    return View(pastomataiContext);
                }

            }
            else if (!String.IsNullOrEmpty(postMachineId))
            {
                if (String.IsNullOrEmpty(state))
                {
                    var pastomataiContext = _context.Package.Include(p => p.FkEndUseridEndUserNavigation)
                                .Include(p => p.FkLoggedInUseridEndUserNavigation)
                                .Include(p => p.FkTerminalidTerminalNavigation);
                    ViewData["PostMachineFilter"] = postMachineId;
                    ViewBag.FkTerminalidTerminal = GetTerminalAddressList();
                    ViewBag.PostMachines = GetPostMachineAddressList();
                    return View(pastomataiContext);
                }
                if (haspostmachine == false)
                {
                    var id = Int16.Parse(postMachineId);
                    var pastomataiContext = _context.Package.Include(p => p.FkEndUseridEndUserNavigation)
                        .Include(p => p.FkLoggedInUseridEndUserNavigation)
                        .Include(p => p.FkTerminalidTerminalNavigation)
                        .Where(p => p.PackageState.Contains(state))
                        .Where(p => p.FkTerminalidTerminal.HasValue.Equals(hasterminal));
                    ViewBag.FkTerminalidTerminal = GetTerminalAddressList();
                    ViewBag.PostMachines = GetPostMachineAddressList();
                    ViewData["PostMachineFilter"] = postMachineId;
                    return View(pastomataiContext);

                }
                else
                {
                    var id = Int16.Parse(postMachineId);
                    var pastomataiContext = _context.Package.Include(p => p.FkEndUseridEndUserNavigation)
                        .Include(p => p.FkLoggedInUseridEndUserNavigation)
                        .Include(p => p.FkTerminalidTerminalNavigation)
                        .Where(p => p.PackageState.Contains(state))
                        .Where(p => p.FkTerminalidTerminal.HasValue.Equals(hasterminal))
                        .Where(p => p.PostMachineBox.FkPostMachineidPostMachineNavigation.IdPostMachine.Equals(id));
                    ViewBag.FkTerminalidTerminal = GetTerminalAddressList();
                    ViewBag.PostMachines = GetPostMachineAddressList();
                    ViewData["PostMachineFilter"] = postMachineId;
                    return View(pastomataiContext);
                }
            }

            else
            {
                var pastomataiContext = _context.Package.Include(p => p.FkEndUseridEndUserNavigation)
                                .Include(p => p.FkLoggedInUseridEndUserNavigation)
                                .Include(p => p.FkTerminalidTerminalNavigation);
                ViewBag.FkTerminalidTerminal = GetTerminalAddressList();
                ViewBag.PostMachines = GetPostMachineAddressList();
                return View(pastomataiContext);
            }
            

        }

        

        // GET: Delivery/UpdateState/5
        public IActionResult UpdateState(int? id, int currentPostMachine, int currentTerminal)
        {
            if (id == null)
            {
                return NotFound();
            }

            var package = _context.Package.Find(id);
            if (package == null)
            {
                return NotFound();
            }
            ViewData["FkEndUseridEndUser"] = new SelectList(_context.EndUser, "IdEndUser", "PhoneNumber", package.FkEndUseridEndUser);
            ViewData["FkLoggedInUseridEndUser"] = new SelectList(_context.LoggedInUser, "IdEndUser", "Email", package.FkLoggedInUseridEndUser);
            ViewData["FkTerminalidTerminal"] = new SelectList(_context.Terminal, "IdTerminal", "PhoneNumber", package.FkTerminalidTerminal);
            ViewData["PostMachineFilter"] = currentPostMachine;
            ViewData["TerminalFilter"] = currentTerminal;
            return View(package);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateState(int id, int currentPostMachine, int currentTerminal, [Bind("PutInTime,CollectionTime,Size,PackageState,IdPackage,FkLoggedInUseridEndUser,FkTerminalidTerminal,FkEndUseridEndUser")] Package package)
        {
            if (id != package.IdPackage)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // take out from post machine
                    if (package.PackageState.Contains("WaitsForCourier"))
                    { package.PackageState = "EnRoute"; }
                    // take out from terminal
                    else if (package.PackageState.Contains("InTerminal"))
                    { package.PackageState = "EnRoute"; }
                    // place in post machine
                    else if (package.PackageState.Contains("EnRoute") && package.FkTerminalidTerminal.HasValue)
                    {
                        package.PackageState = "WaitsForPickup";
                        var postbox = getEmptyByPostMachine(currentPostMachine);
                        package.PostMachineBox = postbox;
                        if (package.PostMachineBox == null)
                        {
                            // post machine is full 
                            return View(package);
                        }
                    }
                    // place in terminal
                    else if (package.PackageState.Contains("EnRoute") && !package.FkTerminalidTerminal.HasValue)
                    {
                        package.PackageState = "InTerminal";
                        // TODO: package is into terminal with id = 20 <-- change it later
                        package.FkTerminalidTerminal = currentTerminal;
                    }

                    //Paprastam useriui

                    if (package.PackageState.Contains("Created"))
                    { package.PackageState = "Activated"; }
                    else if (package.PackageState.Contains("Activated"))
                    { 
                        package.PackageState = "WaitsForCourier";
                        var postbox = getEmptyByPostMachine(currentPostMachine);
                        package.PostMachineBox = postbox;
                        if(package.PostMachineBox == null)
                        {
                            // post machine is full
                            return View(package);
                        }
                    }
                    else if (package.PackageState.Contains("WaitsForPickup"))
                    { 
                        package.PackageState = "Delivered";
                        package.PostMachineBox = null;
                    }                   

                    _context.Update(package);
                        _context.SaveChanges();

pastomatai/Views/Delivery/ConfirmDetails.cshtml
@model pastomatai.Models.Package

@{
    ViewData["Title"] = "ConfirmDetails";
}

<h1>ConfirmDetails</h1>

<h5> Are these details correct?</h5>

<div>
    <h4>Package</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Size)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReceiversNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReceiversNumber)
        </dd>

    </dl>
</div>

<form asp-controller="Delivery" asp-action="UpdateStatesAll" asp-route-currentPostMachine="@ViewData["PostMachineFilter"]" asp-route-currentTerminal="@ViewData["TerminalFilter"]" method="post">
    <input type="hidden" name="IdsToUpdate" id="@Model.IdPackage" value="@Model.IdPackage" />
    <input type="submit" value=" Confirm" /><br>
</form>
<div>

    <a asp-controller="Packages" asp-action="Edit" asp-route-id="@Model.IdPackage">Edit</a>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

pastomatai/Views/Delivery/Index.cshtml
@model IEnumerable<pastomatai.Models.Package>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<h4> Actions within terminals:</h4>

<div>

    <form asp-action="Index" method="get">
        <div class="form-group">
            <table>
                <tr>
                    <td>
                        <select class="form-control" name="TerminalId" asp-items="ViewBag.FkTerminalidTerminal">
                            <option value="" disabled selected>@ViewData["TerminalFilter"]</option>
                        </select>
                    </td>
                    <td>
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </td>
                </tr>
            </table>       
        </div>
    </form>

    <h5>Courier</h5>
    <a asp-action="Index" asp-route-state="EnRoute" asp-route-hasterminal="false" asp-route-terminalId="@ViewData["TerminalFilter"]">Place in terminal</a> |
    <a asp-action="Index" asp-route-state="InTerminal" asp-route-hasterminal="true" asp-route-terminalId="@ViewData["TerminalFilter"]">Take from terminal</a>
</div>
<br />
<div>
    <h4>Actions within post machines:  </h4>

    <form asp-action="Index" method="get">
        <div class="form-group">
            <table>
                <tr>
                    <td>
                        <select class="form-control" name="PostMachineId" asp-items="ViewBag.PostMachines">
                            <option value="" disabled selected>@ViewData["PostMachineFilter"]</option>
                        </select>
                    </td>
                    <td>
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </td>
                </tr>
            </table>          
        </div>
    </form>

    <h5>Courier</h5>
    <a asp-action="Index" asp-route-state="EnRoute" asp-route-hasterminal="true" asp-route-postMachineId="@ViewData["PostMachineFilter"] " asp-route-haspostmachine="false">Place in post machine</a> |
    <a asp-action="Index" asp-route-state="WaitsForCourier" asp-route-hasterminal="false" asp-route-postMachineId="@ViewData["PostMachineFilter"]" asp-route-haspostmachine="true">Take from post machine</a>

    <h5>Client</h5>
    <a asp-action="Index" asp-route-state="Created" asp-route-hasterminal="false" asp-route-postMachineId="@ViewData["PostMachineFilter"]" asp-route-haspostmachine="false">Activate Package</a>
    |
    <a asp-action="Index" asp-route-state="Activated" asp-route-hasterminal="false" asp-route-postMachineId="@ViewData["PostMachineFilter"]" asp-route-haspostmachine="false">Place in post machine</a>
    |
    <a asp-action="Index" asp-route-state="WaitsForPickup" asp-route-hasterminal="true" asp-route-postMachineId="@ViewData["PostMachineFilter"]" asp-route-haspostmachine="true">Take from post machine</a>

</div>
<br />
<div>
    <a asp-action="Index">Back to Full List</a>
</div>

@{
    string notshow = null;
}

<form asp-controller="Delivery" asp-action="UpdateStatesAll" asp-route-currentPostMachine="@ViewData["PostMachineFilter"]" asp-route-currentTerminal="@ViewData["TerminalFilter"]" method="post">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Selected
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PutInTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CollectionTime)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Size)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PackageState)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FkEndUseridEndUserNavigation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FkLoggedInUseridEndUserNavigation)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FkTerminalidTerminalNavigation)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input name="IdsToUpdate" type="checkbox" id="@item.IdPackage" value="@item.IdPackage" />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PutInTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CollectionTime)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Size)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PackageState)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FkEndUseridEndUserNavigation.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FkLoggedInUseridEndUserNavigation.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FkTerminalidTerminalNavigation.PhoneNumber)
                    </td>
                    <td>
                        @if (item.PackageState.Contains("Created"))
                        {
                            notshow = item.PackageState;
                            <div>
                                <a asp-action="UpdateState" asp-route-id="@item.IdPackage" asp-route-currentPostMachine="@ViewData["PostMachineFilter"]" asp-route-currentTerminal="@ViewData["TerminalFilter"]">Activate package</a>
                            </div>

                        }
                        else if (item.PackageState.Contains("WaitsForPickup"))
                        {
                            notshow = item.PackageState;
                            <a asp-action="PinConfirmation" asp-route-id="@item.IdPackage"  asp-route-currentPostMachine="@ViewData["PostMachineFilter"]" asp-route-currentTerminal="@ViewData["TerminalFilter"]">Withdraw package</a>
                        }
                        else if (item.PackageState.Contains("Activated"))
                        {
                            notshow = item.PackageState;
                            <a asp-action="ConfirmDetails" asp-route-id="@item.IdPackage"  asp-route-currentPostMachine="@ViewData["PostMachineFilter"]" asp-route-currentTerminal="@ViewData["TerminalFilter"]">Place package into post machine</a>
                        }
                        else
                        {
                            <a asp-action="UpdateState" asp-route-id="@item.IdPackage" asp-route-currentPostMachine="@ViewData["PostMachineFilter"]" asp-route-currentTerminal="@ViewData["TerminalFilter"]">Update state</a>
                        }


                    </td>
                </tr>
            }
        </tbody>
    </table>
    @if (String.IsNullOrEmpty(notshow))
    {
        <input type="submit" value=" Update selected" /><br>
    }

</form>

pastomatai/Views/Delivery/PinConfirmation.cshtml
@model pastomatai.Models.Package

@{
    ViewData["Title"] = "PinConfirmation";
}

<h1>Submit pin</h1>

<div>
    <form asp-action="PinConfirmation" asp-route-packageId="@Model.IdPackage" method="post">
        <div class="form-actions no-color">
            <p>
                Pin Code: <input type="text" name="Pin" />
                <input type="submit" value="Submit" class="btn btn-default" />
            </p>
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

pastomatai/Views/Delivery/UpdateState.cshtml
@model pastomatai.Models.Package

@{
    ViewData["Title"] = "UpdateState";
}

<h1>UpdateState</h1>

<h4>Package</h4>

<h5> Do you want to update this package's state?</h5>

<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.PutInTime)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.PutInTime)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.CollectionTime)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.CollectionTime)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Size)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Size)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.PackageState)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.PackageState)
    </dd>
</dl>
<div class="row">
    <div class="col-md-4">
        <form asp-action="UpdateState" asp-route-currentPostMachine="@ViewData["PostMachineFilter"]" asp-route-currentTerminal="@ViewData["TerminalFilter"]">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PutInTime" />
            <input type="hidden" asp-for="CollectionTime" />
            <input type="hidden" asp-for="Size" />
            <input type="hidden" asp-for="PackageState" />
            <input type="hidden" asp-for="IdPackage" />
            <input type="hidden" asp-for="FkLoggedInUseridEndUser" />
            <input type="hidden" asp-for="FkTerminalidTerminal" />
            <input type="hidden" asp-for="FkEndUseridEndUser" />
            <div class="form-group">
                <input type="submit" value="Confirm" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <p>
        <a href="javascript:void(0);" onclick="history.go(-1);">Back</a>
    </p>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

pastomatai/Views/Delivery/UpdateStatesAll.cshtml
@model IEnumerable<pastomatai.Models.Package>

@{
    ViewData["Title"] = "UpdateStatesAll";
}

<h1>UpdateStatesAll</h1>
<hr />

<h3>Packages states' have been changed.</h3>
<div>
    <a asp-action="Index">Back to List</a>
</div>